apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.databackup.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.databackup.fullname" . }}
spec:
  serviceName: {{ template "elasticsearch.databackup.fullname" . }}
  replicas: {{ .Values.databackup.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}
        component: "{{ .Values.databackup.name }}"
        release: {{ .Release.Name }}
        role: data
        {{- if .Values.databackup.podAnnotations }}
      annotations:
{{ toYaml .Values.databackup.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "elasticsearch.serviceAccountName.databackup" . }}
{{- if .Values.databackup.priorityClassName }}
      priorityClassName: "{{ .Values.databackup.priorityClassName }}"
{{- end }}
      securityContext:
        fsGroup: 1000
      {{- if or .Values.databackup.antiAffinity .Values.databackup.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.databackup.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "elasticsearch.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.databackup.name }}"
      {{- else if eq .Values.databackup.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "elasticsearch.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.databackup.name }}"
      {{- end }}
      {{- with .Values.databackup.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.databackup.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.databackup.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.databackup.tolerations }}
      tolerations:
{{ toYaml .Values.databackup.tolerations | indent 8 }}
{{- end }}
      initContainers:
{{- if .Values.sysctlInitContainer.enabled }}
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: {{ .Values.initImage.pullPolicy | quote }}
        resources:
{{ toYaml .Values.databackup.initResources | indent 12 }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
{{- end }}
      - name: "chown"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.databackup.initResources | indent 12 }}
        command:
        - /bin/bash
        - -c
        - >
          set -e;
          set -x;
          chown elasticsearch:elasticsearch /usr/share/elasticsearch/data;
          for datadir in $(find /usr/share/elasticsearch/data -mindepth 1 -maxdepth 1 -not -name ".snapshot"); do
            chown -R elasticsearch:elasticsearch $datadir;
          done;
          chown elasticsearch:elasticsearch /usr/share/elasticsearch/logs;
          for logfile in $(find /usr/share/elasticsearch/logs -mindepth 1 -maxdepth 1 -not -name ".snapshot"); do
            chown -R elasticsearch:elasticsearch $logfile;
          done
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
{{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
{{- end }}
{{- if .Values.cluster.plugins }}
{{ include "plugin-installer" . | indent 6 }}
{{- end }}
      containers:
      - name: elasticsearch
        env:
        - name: DISCOVERY_SERVICE
          value: {{ template "elasticsearch.fullname" . }}-discovery
        - name: NODE_MASTER
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: NODE_TYPE
          value: "cold"
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.databackup.heapSize }} -Xmx{{ .Values.databackup.heapSize }} {{ .Values.cluster.additionalJavaOpts }} {{ .Values.databackup.additionalJavaOpts }}"
        {{- if .Values.databackup.paths }}
        - name: PATH_DATA
          value: {{ join "," .Values.databackup.paths }}
        {{- end }}
        {{- range $key, $value :=  .Values.cluster.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 9300
          name: transport
{{ if .Values.databackup.exposeHttp }}
        - containerPort: 9200
          name: http
{{ end }}
        resources:
{{ toYaml .Values.databackup.resources | indent 12 }}
        readinessProbe:
{{ toYaml .Values.databackup.readinessProbe | indent 10 }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
{{- if .Values.databackup.persistence.useLocalDisk }}
  {{- range until (int .Values.databackup.persistence.localDiskCount) }}
        - mountPath: /mnt/disks/ssd{{ . }}
          name: data{{ . }}
  {{- end }}
{{- end }}
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
{{- if .Values.cluster.plugins }}
        - mountPath: /usr/share/elasticsearch/plugins/
          name: plugindir
{{- end }}
{{- if hasPrefix "2." .Values.appVersion }}
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
{{- end }}
{{- if hasPrefix "5." .Values.appVersion }}
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: config
          subPath: log4j2.properties
{{- end }}
{{- if .Values.cluster.keystoreSecret }}
        - name: keystore
          mountPath: "/usr/share/elasticsearch/config/elasticsearch.keystore"
          subPath: elasticsearch.keystore
          readOnly: true
{{- end }}
{{- if .Values.databackup.hooks.drain.enabled }}
        - name: config
          mountPath: /pre-stop-hook.sh
          subPath: pre-stop-hook.sh
        - name: config
          mountPath: /post-start-hook.sh
          subPath: post-start-hook.sh
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash","/pre-stop-hook.sh"]
          postStart:
            exec:
              command: ["/bin/bash","/post-start-hook.sh"]
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.databackup.terminationGracePeriodSeconds }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "elasticsearch.fullname" . }}
{{- if .Values.cluster.plugins }}
      - name: plugindir
        emptyDir: {}
{{- end }}
{{- if .Values.cluster.keystoreSecret }}
      - name: keystore
        secret:
          secretName: {{ .Values.cluster.keystoreSecret }}
{{- end }}
  {{- if not .Values.databackup.persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- end }}
  {{- if .Values.databackup.persistence.useLocalDisk }}
    {{- range until (int .Values.databackup.persistence.localDiskCount) }}
      - name: data{{ . }}
        hostPath:
          path: /mnt/disks/ssd{{ . }}
    {{- end }}
  {{- end }}
  updateStrategy:
    type: {{ .Values.databackup.updateStrategy.type }}
  {{- if and .Values.databackup.persistence.enabled (not .Values.databackup.persistence.useLocalDisk) }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.databackup.persistence.name }}
    spec:
      accessModes:
        - {{ .Values.databackup.persistence.accessMode | quote }}
    {{- if .Values.databackup.persistence.storageClass }}
    {{- if (eq "-" .Values.databackup.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.databackup.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.databackup.persistence.size }}"
  {{- end }}
